version: "3"
services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3.7.0-debian-10-r188'
    networks:
      kafka:
        aliases:
          - zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'docker.io/bitnami/kafka:2.8.1-debian-10-r31'
    networks:
      kafka:
        aliases:
          - kafka
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL://127.0.0.1:9092
      - KAFKA_CREATE_TOPICS=chat_message
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

    depends_on:
      - zookeeper

networks:
  kafka: